// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAgent(arg1) {
  return window['go']['repository']['Repo']['DeleteAgent'](arg1);
}

export function DeleteHoliday(arg1) {
  return window['go']['repository']['Repo']['DeleteHoliday'](arg1);
}

export function DeleteIndustry(arg1) {
  return window['go']['repository']['Repo']['DeleteIndustry'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['repository']['Repo']['DeleteJob'](arg1);
}

export function DeleteLocation(arg1) {
  return window['go']['repository']['Repo']['DeleteLocation'](arg1);
}

export function DeleteRate(arg1) {
  return window['go']['repository']['Repo']['DeleteRate'](arg1);
}

export function GetAgentById(arg1) {
  return window['go']['repository']['Repo']['GetAgentById'](arg1);
}

export function GetHolidayByDate(arg1) {
  return window['go']['repository']['Repo']['GetHolidayByDate'](arg1);
}

export function GetHolidayById(arg1) {
  return window['go']['repository']['Repo']['GetHolidayById'](arg1);
}

export function GetIndustryById(arg1) {
  return window['go']['repository']['Repo']['GetIndustryById'](arg1);
}

export function GetJobById(arg1) {
  return window['go']['repository']['Repo']['GetJobById'](arg1);
}

export function GetJobsByDate(arg1, arg2) {
  return window['go']['repository']['Repo']['GetJobsByDate'](arg1, arg2);
}

export function GetJobsByFilter(arg1, arg2, arg3, arg4) {
  return window['go']['repository']['Repo']['GetJobsByFilter'](arg1, arg2, arg3, arg4);
}

export function GetLocationById(arg1) {
  return window['go']['repository']['Repo']['GetLocationById'](arg1);
}

export function GetRateById(arg1) {
  return window['go']['repository']['Repo']['GetRateById'](arg1);
}

export function GetRatesByAgentTypeAndCategory(arg1, arg2, arg3) {
  return window['go']['repository']['Repo']['GetRatesByAgentTypeAndCategory'](arg1, arg2, arg3);
}

export function ListAllAgents() {
  return window['go']['repository']['Repo']['ListAllAgents']();
}

export function ListAllIndustries() {
  return window['go']['repository']['Repo']['ListAllIndustries']();
}

export function ListAllLocations() {
  return window['go']['repository']['Repo']['ListAllLocations']();
}

export function ListAllRates() {
  return window['go']['repository']['Repo']['ListAllRates']();
}

export function ListHolidays(arg1, arg2) {
  return window['go']['repository']['Repo']['ListHolidays'](arg1, arg2);
}

export function ListJobs(arg1, arg2, arg3) {
  return window['go']['repository']['Repo']['ListJobs'](arg1, arg2, arg3);
}

export function SaveAgent(arg1) {
  return window['go']['repository']['Repo']['SaveAgent'](arg1);
}

export function SaveHoliday(arg1) {
  return window['go']['repository']['Repo']['SaveHoliday'](arg1);
}

export function SaveIndustry(arg1) {
  return window['go']['repository']['Repo']['SaveIndustry'](arg1);
}

export function SaveJob(arg1) {
  return window['go']['repository']['Repo']['SaveJob'](arg1);
}

export function SaveLocation(arg1) {
  return window['go']['repository']['Repo']['SaveLocation'](arg1);
}

export function SaveRate(arg1) {
  return window['go']['repository']['Repo']['SaveRate'](arg1);
}
