// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocationService() {
  return window['go']['settings']['Settings']['GetLocationService']();
}

export function GetSettings() {
  return window['go']['settings']['Settings']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['settings']['Settings']['SaveSettings'](arg1);
}

export function SetLocationService(arg1) {
  return window['go']['settings']['Settings']['SetLocationService'](arg1);
}
