// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function GetLocationService():Promise<settings.LocationService>;

export function GetSettings():Promise<settings.Settings>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SetLocationService(arg1:settings.LocationService):Promise<void>;
