// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteHoliday(arg1) {
  return window['go']['main']['App']['DeleteHoliday'](arg1);
}

export function DeleteIndustry(arg1) {
  return window['go']['main']['App']['DeleteIndustry'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function DeleteLocation(arg1) {
  return window['go']['main']['App']['DeleteLocation'](arg1);
}

export function DeleteRate(arg1) {
  return window['go']['main']['App']['DeleteRate'](arg1);
}

export function GetAgentById(arg1) {
  return window['go']['main']['App']['GetAgentById'](arg1);
}

export function GetCurrentDir() {
  return window['go']['main']['App']['GetCurrentDir']();
}

export function GetHolidayByDate(arg1) {
  return window['go']['main']['App']['GetHolidayByDate'](arg1);
}

export function GetHolidayById(arg1) {
  return window['go']['main']['App']['GetHolidayById'](arg1);
}

export function GetIndustryById(arg1) {
  return window['go']['main']['App']['GetIndustryById'](arg1);
}

export function GetJobById(arg1) {
  return window['go']['main']['App']['GetJobById'](arg1);
}

export function GetJobsByDate(arg1, arg2) {
  return window['go']['main']['App']['GetJobsByDate'](arg1, arg2);
}

export function GetJobsByFilter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetJobsByFilter'](arg1, arg2, arg3, arg4);
}

export function GetLocationById(arg1) {
  return window['go']['main']['App']['GetLocationById'](arg1);
}

export function GetRateById(arg1) {
  return window['go']['main']['App']['GetRateById'](arg1);
}

export function GetRatesByAgentTypeAndCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRatesByAgentTypeAndCategory'](arg1, arg2, arg3);
}

export function ListAllAgents() {
  return window['go']['main']['App']['ListAllAgents']();
}

export function ListAllIndustries() {
  return window['go']['main']['App']['ListAllIndustries']();
}

export function ListAllLocations() {
  return window['go']['main']['App']['ListAllLocations']();
}

export function ListAllRates() {
  return window['go']['main']['App']['ListAllRates']();
}

export function ListHolidays(arg1, arg2) {
  return window['go']['main']['App']['ListHolidays'](arg1, arg2);
}

export function ListJobs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListJobs'](arg1, arg2, arg3);
}

export function SaveAgent(arg1) {
  return window['go']['main']['App']['SaveAgent'](arg1);
}

export function SaveHoliday(arg1) {
  return window['go']['main']['App']['SaveHoliday'](arg1);
}

export function SaveIndustry(arg1) {
  return window['go']['main']['App']['SaveIndustry'](arg1);
}

export function SaveJob(arg1) {
  return window['go']['main']['App']['SaveJob'](arg1);
}

export function SaveLocation(arg1) {
  return window['go']['main']['App']['SaveLocation'](arg1);
}

export function SaveRate(arg1) {
  return window['go']['main']['App']['SaveRate'](arg1);
}
