// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteHoliday(arg1) {
  return window['go']['main']['App']['DeleteHoliday'](arg1);
}

export function DeleteIndustry(arg1) {
  return window['go']['main']['App']['DeleteIndustry'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function DeleteRate(arg1) {
  return window['go']['main']['App']['DeleteRate'](arg1);
}

export function GetAgentById(arg1) {
  return window['go']['main']['App']['GetAgentById'](arg1);
}

export function GetCurrentDir() {
  return window['go']['main']['App']['GetCurrentDir']();
}

export function GetHolidayById(arg1) {
  return window['go']['main']['App']['GetHolidayById'](arg1);
}

export function GetIndustryById(arg1) {
  return window['go']['main']['App']['GetIndustryById'](arg1);
}

export function GetJobById(arg1) {
  return window['go']['main']['App']['GetJobById'](arg1);
}

export function GetRateById(arg1) {
  return window['go']['main']['App']['GetRateById'](arg1);
}

export function ListAllAgents() {
  return window['go']['main']['App']['ListAllAgents']();
}

export function ListAllHolidays() {
  return window['go']['main']['App']['ListAllHolidays']();
}

export function ListAllIndustries() {
  return window['go']['main']['App']['ListAllIndustries']();
}

export function ListAllJobs() {
  return window['go']['main']['App']['ListAllJobs']();
}

export function ListAllRates() {
  return window['go']['main']['App']['ListAllRates']();
}

export function SaveAgent(arg1) {
  return window['go']['main']['App']['SaveAgent'](arg1);
}

export function SaveHoliday(arg1) {
  return window['go']['main']['App']['SaveHoliday'](arg1);
}

export function SaveIndustry(arg1) {
  return window['go']['main']['App']['SaveIndustry'](arg1);
}

export function SaveJob(arg1) {
  return window['go']['main']['App']['SaveJob'](arg1);
}

export function SaveRate(arg1) {
  return window['go']['main']['App']['SaveRate'](arg1);
}
