// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDatabase():Promise<string>;

export function ExportJob():Promise<string>;

export function GetCurrentDir():Promise<string>;
