// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function GetAgentById(arg1:number):Promise<repository.Agent>;

export function GetCurrentDir():Promise<string>;
