// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgentById(arg1) {
  return window['go']['main']['App']['GetAgentById'](arg1);
}

export function GetCurrentDir() {
  return window['go']['main']['App']['GetCurrentDir']();
}
